name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  release-charts:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config init.defaultBranch main

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - name: Run chart-releaser
      uses: justingarfield/library-chart-releaser-action@v0.1.17
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
