name: "Pre-commit consistency check"

on:
  workflow_dispatch:
    branches:
      - 'main'
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.head_ref || github.run_id}}-precommit
  cancel-in-progress: true

jobs:
  pre-commit-check:
    name: Run pre-commit checks
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: shell
        filters: |
          addedOrModified:
            - added|modified: '**'

    # run only if changed files were detected
    - name: Run against changes
      uses: pre-commit/action@v3.0.0
      if: steps.filter.outputs.addedOrModified == 'true'
      with:
        extra_args: --config .ci/pre-commit/.pre-commit-config.yaml --files ${{ steps.filter.outputs.addedOrModified_files }}

    # run if no changed files were detected (e.g. workflow_dispatch on main branch)
    - name: Run against all files
      uses: pre-commit/action@v3.0.0
      if: steps.filter.outputs.addedOrModified != 'true'
      with:
        extra_args: --config .ci/pre-commit/.pre-commit-config.yaml --all-files
